[package]
name = "deep-space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bones = { path = "../bones-engine" }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"